openapi: 3.0.0
x-stoplight:
  id: a1lowzykezjb5
info:
  title: Admission
  version: '1.0'
  description: |-
    ### 1. But du service
    Ce service permet de gérer les établissements d'enseignement fréquentés.

    ### 2. Description sommaire du contexte
    Ce service fournit un ensemble d'opérations qui permettent d'accéder aux informations de l'établissement d'enseignement fréquenté.

    ### 3. Fréquence d'appel
    L'information sur l'établissement d'enseignement fréquenté est recueillie à la demande.

    ### 4. Source des données
    Les informations relatives à l'établissement d'enseignement fréquenté se trouvent dans la table ETABL_ENSGN_FREQN de la base de données Admission.

    ### 5. Volume de production
    S/O

    ### 6. Cible
    [ServiceEtablissementEnseignementFrequente](https://dev.monportail.ulaval.ca/sites/set/tronc-SNAPSHOT/set-apis/apidocs/ca/ulaval/gde/set/apis/admission/candidats/etudesanterieures/etablissementsenseignementfrequentes/ServiceEtablissementEnseignementFrequente.html) (javadoc).

    ### 7. Conditions préalables
    S/O
  contact:
    name: Isabelle Filiatrault
    email: isabelle.filiatrault@dti.ulaval.ca
servers:
  - url: 'https://monportail.test.ulaval.ca/etudes/v1'
    description: test
  - url: 'https://monportail.testpr.ulaval.ca/etudes/v1'
    description: testpr
  - url: 'https://monportail.app.ulaval.ca/etudes/v1'
    description: app
  - url: 'https://monportail.apppr.ulaval.ca/etudes/v1'
    description: apppr
  - url: 'https://monportail.ulaval.ca/etudes/v1'
    description: prod
paths:
  /admission/candidats/dossieradmission:
    put:
      summary: Créer un dossier d'admission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ni:
                  type: string
      responses:
        '200':
          description: Dossier créé avec succès
          content:
            application/json:
              schema:
                type: string
                format: uuid
    get:
      summary: Obtenir un dossier d'admission par ID ou NI
      parameters:
        - in: query
          name: ni
          schema:
            type: string
      responses:
        '200':
          description: Le dossier d'admission demandé
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DossierAdmission'
      operationId: get-dossieradmission
      description: Rechercher des dossiers d'admission.
  /admission/candidats/etudesanterieures/etablissementsenseignementfrequentes:
    parameters: []
    get:
      summary: rechercherEtablissementsEnseignementFrequentes
      operationId: rechercherEtablissementsEnseignementFrequentes
      responses:
        '200':
          description: Le résultat de la recherche
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultats:
                    type: array
                    x-stoplight:
                      id: j6whbfy0rf5pg
                    items:
                      $ref: '#/components/schemas/EtablissementEnseignementFrequente'
                      x-stoplight:
                        id: gev6f9uzvoad4
                required:
                  - resultats
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: idDossierAdmission
          description: Identifiant d'établissement d'enseignement fréquenté
          required: false
        - schema:
            type: string
            minLength: 2
            maxLength: 2
          in: query
          name: codePays
          description: Le code pays de l'établissement
      description: |-
        Recherche
        - Aucune règle à vérifier
        - Sélectionner le ou les occurrences dans la table établissement enseignement fréquenté de l'Admission pour un candidat
      tags:
        - candidats/etudesanterieures
    put:
      summary: creerEtablissementEnseignementFrequente
      operationId: put-admission-candidats-etudesanterieures-etablissementsenseignementfrequentes
      responses:
        '200':
          description: 'L''établissement d''enseignement fréquenté créé :-)'
          content:
            application/json:
              schema:
                type: string
                format: uuid
      description: |-
        Créer un établissement d'enseignement fréquenté :
        - Vérifier l'ensemble des règles (sauf 13, 14 et 15) décrites dans la section Règles fonctionnelles
        - Si le dossier n'est pas à confirmer (indicateur "Doit confirmer" à 'N') alors rendre le dossier à confirmer (indicateur "Doit confirmer" à 'O')
        - Créer l’établissement d'enseignement fréquenté dans l'Admission.
        - Déterminer l'indicateur de déclaration du candidat modifiée (Opération "Déterminer l'indicateur de déclaration du candidat modifiée" du service ServiceDossierAdmission).
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EtablissementEnseignementFrequente'
              description: JERONIMO
        description: |-
          L'établissement d'enseignement fréquenté à créer.

          Si l'établissement n'a aucune FormationSuivie, la confirmation du DossierAdmission sera demandée.

          Validations:
          - etablissementEnseignementFrequente non null
          - etablissementEnseignementFrequente.idDossierAdmission non null
          - etablissementEnseignementFrequente.choixEtablissementEnseignement non null
          - etablissementEnseignementFrequente.choixEtablissementEnseignement.idEtablissement ou etablissementEnseignementFrequente.choixEtablissementEnseignement.nomEtablissementEnseignement non null (mutuellement exclusif)
          - si etablissementEnseignementFrequente.choixEtablissementEnseignement.idEtablissement non null :
          - etablissementEnseignementFrequente.choixEtablissementEnseignement.codePays est null
          - etablissementEnseignementFrequente.choixEtablissementEnseignement.codeProvinceEtat est null
          - si etablissementEnseignementFrequente.choixEtablissementEnseignement.nomEtablissementEnseignement non null :
          - etablissementEnseignementFrequente.nomEtablissementEnseignement taille maximale de 50 caractères
          - etablissementEnseignementFrequente.choixEtablissementEnseignement.codePays est non null
          - etablissementEnseignementFrequente.choixEtablissementEnseignement.codeProvinceEtat est non null
      tags:
        - candidats/etudesanterieures
  '/admission/candidats/etudesanterieures/etablissementsenseignementfrequentes/{idetablissementenseignementfrequente}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: idetablissementenseignementfrequente
        in: path
        required: true
        description: L'identifiant de l'établissement d'enseignement fréquenté
    get:
      summary: obtenirEtablissementEnseignementFrequente
      tags:
        - candidats/etudesanterieures
      responses:
        '200':
          description: L'établissement d'enseignement fréquenté
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EtablissementEnseignementFrequente'
      operationId: get-admission-candidats-etudesanterieures-etablissementsenseignementfrequentes-idetablissementenseignementfrequente
      description: Obtenir un établissement d'enseignement fréquenté.
  /admission/etablissementenseignement:
    put:
      summary: Créer un établissement d'enseignement
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: uuid
      operationId: put-admission-etablissementenseignement
      description: Ajouter un etablissement d'enseignement
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nomEtablissementEnseignement:
                  type: string
                  x-stoplight:
                    id: rzny11i60dstl
                  minLength: 2
                codePays:
                  type: string
                  x-stoplight:
                    id: my1dd04vtj7hq
                  minLength: 2
                  maxLength: 2
              required:
                - nomEtablissementEnseignement
                - codePays
        description: Les informations nécessaires pour la création.
    get:
      summary: ''
      operationId: get-admission-etablissementenseignement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EtablissementEnseignement'
      description: Rechercher des établissements d'enseignement.
  '/admission/candidats/dossieradmission/{iddossieradmission}/etablissementenseignementfrequente':
    parameters:
      - schema:
          type: string
        name: iddossieradmission
        in: path
        required: true
    put:
      summary: Créer un établissement d'enseignement fréquenté
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: uuid
      operationId: put-etablissementenseignementfrequente
      description: Ajouter un établissement d'enseignement fréquenté dans un dossier d'admission.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                idEtablissementEnseignement:
                  type: string
                  x-stoplight:
                    id: xczdkfm5k2c6e
                  format: uuid
              required:
                - idEtablissementEnseignement
components:
  schemas:
    EtablissementEnseignementFrequente:
      title: EtablissementEnseignementFrequente
      x-stoplight:
        id: 252m3g6m0dd43
      x-tags:
        - entite
      type: object
      description: Représente les établissements d'enseignement fréquentés de l'individu.
      properties:
        idEtablissementEnseignementFrequente:
          type: string
          format: uuid
          x-stoplight:
            id: xfxjjbf0xvse2
          description: L'identifiant de l'établissement d'enseignement fréquenté.
          readOnly: true
        idDossierAdmission:
          type: string
          x-stoplight:
            id: 3vawanjsov64r
          format: uuid
          description: Identifiant du dossier d'admission.
        choixEtablissementEnseignement:
          $ref: '#/components/schemas/EtablissementEnseignement'
        idsFormationsSuivies:
          type: array
          x-stoplight:
            id: punwfl1y9jk1e
          uniqueItems: true
          description: L'ensemble des formations suivies par le candidat dans cet établissement
          items:
            x-stoplight:
              id: vthc6z4tt7152
            type: string
            format: uuid
        version:
          type: integer
          x-stoplight:
            id: dcr6eeh3dfz6l
          example: 3
          description: La version de l'etablissement d'enseignement
      required:
        - idEtablissementEnseignementFrequente
        - idDossierAdmission
        - choixEtablissementEnseignement
        - idsFormationsSuivies
        - version
    EtablissementEnseignement:
      title: EtablissementEnseignement
      x-stoplight:
        id: dzf1ras2i54ps
      type: object
      properties:
        idEtablissement:
          type: string
          x-stoplight:
            id: yjp4g16o3z6jr
        nomEtablissementEnseignement:
          type: string
          x-stoplight:
            id: tdg5pzjk9rv1e
        codePays:
          type: string
          x-stoplight:
            id: 5mjznhparwxwk
      required:
        - nomEtablissementEnseignement
        - codePays
    DossierAdmission:
      title: DossierAdmission
      x-stoplight:
        id: np32sdh9pufxt
      type: object
      properties:
        idDossierAdmission:
          type: string
          x-stoplight:
            id: 4k1179ymeyk7v
          format: uuid
        ni:
          type: string
          x-stoplight:
            id: fjrtz5a50sgxj
  securitySchemes: {}
